### ISSUE TITLE
Bug Reports/Suggestions/Support

### ISSUE THREAD

**Issue by yuesha-yc** [GregTech6-Unofficial/GregTech6-Unofficial#1]
You can leave your bug reports or suggestions of the Mod or any support information you want to provide in the issues. The GT6U team will check the issues as soon as possible.

**Comment by GREIKA** [comment]
Suggestion: GT6 has a lot of unused superheavy elements, such as Untripentium, Untriseptium, Unhexpentium, etc. It would be cool if those elements could be given a use in the endgame. Maybe synthesize them using the particle accelerator? The only problem would be to come up with the recipes. For instance, Ununennium (Element 119) has a decent amount of documentation when it comes to its synthesis (bombard a target of einsteinium-254 with calcium-48 ions in a particle accelerator), but you probably won't find anything in regards to Trinilnilium (Element 300).
