### ISSUE TITLE
Tinker's Gregworks (GT6 branch) does not recognize any GT6U version past 6.14.01

### ISSUE THREAD

**Issue by GREIKA** [GregTech6-Unofficial/GregTech6-Unofficial#16]
Hello! The latest version of GT6U (6.14.03) and version 6.14.02 seem to cause the [GT6 branch of Tinker's Gregworks](https://github.com/Vexatos/TinkersGregworks/tree/gregtech6) to not recognize GT6U. Every version up to 6.14.01 seems to work fine. [Here's the log](https://hastebin.com/eruxihumop.md) (see line 1).

**Comment by yuesha-yc** [comment]
This is because I changed the main version of the mod to GT6U-1710. Do you have a Git repo or something for the Tinker's Gregwork so that I can send a PR to solve the problem?

**Comment by GREIKA** [comment]
here it is: https://github.com/Vexatos/TinkersGregworks/tree/gregtech6

**Comment by yuesha-yc** [comment]
6.15.00
