### ISSUE TITLE
Crash when both NetheritePlus and Netherlicious are loaded

### ISSUE THREAD

**Issue by geodk00** [GregTech6-Unofficial/GregTech6-Unofficial#18]
Crash report: [https://ghostbin.co/paste/xmucv](url)

Doesn't happen when only one of them is loaded.
Works with vanilla GT6 6.14.01

**Comment by yuesha-yc** [comment]
I will look at this soon, please use 6.14.07 for now.

**Comment by yuesha-yc** [comment]
NVM

**Comment by yuesha-yc** [comment]
Closed, fixed in 6.15.04
