### ISSUE TITLE
Fluid solidifier recipes?

### ISSUE THREAD

**Issue by TLaviron** [GregTech6-Unofficial/GregTech6-Unofficial#23]
I have some stock of molten metal (chromium) that I need to turn into solids, but there does not seem to be a way to use the fluid solidifier.
There seem to be no recipes for the machine (or at least they don't show up in NEI) and no way to put the molten metal into the machine (maybe due to the lack of recipes).

**Comment by Miradae** [comment]
You can cast your molten metals in molds. No idea why there is a need of a Fluid Solidifier, it's probably an artifact from the dev before yueh

**Comment by yuesha-yc** [comment]
Yeah @Miradae is correct, I won't do further actions to the fluid solidifiers.
