### ISSUE TITLE
Sorting Cycle Error (ForgeMultipart)

### ISSUE THREAD

**Issue by mechobree** [GregTech6-Unofficial/GregTech6-Unofficial#24]
When in a modpack I was making, I got this error for awhile, and I tested it through to find that it is refusing to load when Multipart is installed
![java_17-11-2020-42 17](https://user-images.githubusercontent.com/29335214/99454457-6f567380-28f4-11eb-835d-0b98f97a846d.png)

[fml-client-latest.log](https://gist.github.com/mechobree/498d8ae9f5078c9e9cf48c1072f5dd41)

**Comment by yuesha-yc** [comment]
I wonder if you can try using version 347

> Forge Multipart
> You have to use Version 347 as mentioned above, any other Version, including the usually automatically downloaded ones won’t work, and will throw you a Mod Sorting Error, which in on itself is actually a Forge Bug regarding the "after:*" notation that FMP happens to use.

This is quoted from https://gregtech.overminddl1.com/downloads/gregtech_1.7.10/index.html

**Comment by mechobree** [comment]
> 
> 
> I wonder if you can try using version 347
> 
> > Forge Multipart
> > You have to use Version 347 as mentioned above, any other Version, including the usually automatically downloaded ones won’t work, and will throw you a Mod Sorting Error, which in on itself is actually a Forge Bug regarding the "after:*" notation that FMP happens to use.
> 
> This is quoted from https://gregtech.overminddl1.com/downloads/gregtech_1.7.10/index.html

I'll try that once I get my pc set up again, I'll let you know if it works or not

**Comment by mechobree** [comment]
> 
> 
> I wonder if you can try using version 347
> 
> > Forge Multipart
> > You have to use Version 347 as mentioned above, any other Version, including the usually automatically downloaded ones won’t work, and will throw you a Mod Sorting Error, which in on itself is actually a Forge Bug regarding the "after:*" notation that FMP happens to use.
> 
> This is quoted from https://gregtech.overminddl1.com/downloads/gregtech_1.7.10/index.html

yep that did the trick
