### ISSUE TITLE
Oilcleaner making explosion sound while running

### ISSUE THREAD

**Issue by Miradae** [GregTech6-Unofficial/GregTech6-Unofficial#29]
I noticed when i run my oil cleaner it sounds like i overcharged it and it explodes, but only the sound is playing, no actual explosion. 
Now i checked the code and found this line 

@Override public void onProcessStarted() {UT.Sounds.send(SFX.MC_EXPLODE, this); super.onProcessStarted();}

Is there a reason it plays that super annoying sound on repeat?It really feels like it was setup wrong with that explosion sound playing

**Comment by yuesha-yc** [comment]
Can you provide me address of this code? I think the sound it referenced is wrong. I am pretty sure @TeinFanshu added this machine so I will also ask him about his actual intention. Thank you!

**Comment by Miradae** [comment]
https://github.com/GregTech6-Unofficial/GregTech6-Unofficial/blob/a4c5bf8076cd98c7442a3d31375d8f3a8cad8c21/src/main/java/gregtech/tileentity/multiblocks/MultiTileEntityOilCleaner.java
