### ISSUE TITLE
[Suggestion] NEI recipe numbers with separator and item tooltips

### ISSUE THREAD

**Issue by Miradae** [GregTech6-Unofficial/GregTech6-Unofficial#35]
Currently reading many of the GT6u recipes can be cumbersome since there is no 1000s separator. Same for tooltips on things like tanks, drums, batteries etc

**Comment by yuesha-yc** [comment]
I think Greg added separators recently?

**Comment by Miradae** [comment]
Not that i know of, I added separators to WAILA with OmniOcular.
I asked in bears discord for it and bear said Greg MIGHT add it but forget about it all the time. There is also no mentioning about it in the changelog

**Comment by yuesha-yc** [comment]
I can confirm Greg added it since I am in the new codebase. Please wait for the new release.
