### ISSUE TITLE
Can't connect wires to lightning rod output

### ISSUE THREAD

**Issue by TLaviron** [GregTech6-Unofficial/GregTech6-Unofficial#40]
Hello,
I am trying to collect energy from a lightning rod, but I can't connect any wires or cables to the output.
I've tried different sizes and voltages but the lightning rod output just does not seem to be recognized as an electricity source.

If this behavior is intended, I am not sure how to extract energy from it...

**Comment by yuesha-yc** [comment]
This is intended. You should use a transformer or battery box to connect to the lightning rod output. Closing.
