### ISSUE TITLE
你会讨厌他们的

### ISSUE THREAD

**Issue by AserJoker** [GregTech6-Unofficial/GregTech6-Unofficial#6]
机械臂，泵，传送带可以贴在机械方块的任意面，但是不起作用，bug还是特性？另外吐槽一句 虽然无法设定一个方块的输入输出面很科学，但是强迫症快被杂乱的工厂逼疯了

**Comment by yuesha-yc** [comment]
Machine Casings are neither inventory or fluid tank so of course they cannot work. Robot Arms, Electric Pumps, and Conveyors can be put on any TE. This is not an issue.
